# Generated by Django 2.0.7 on 2018-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
